#!/bin/sh

set -e

FLECTRA_LIB_DIR=/var/lib/flectra
FLECTRA_USER="flectra"
FLECTRA_GROUP="flectra"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    remove)
        deluser --quiet --system $FLECTRA_USER || true
        delgroup --quiet --system --only-if-empty $FLECTRA_GROUP || true
        	# remove workaround for https://bugs.debian.org/1059326
        if [ -L ${GSFONTS_DIR}/n021003l.pfb ] ; then
            rm ${GSFONTS_DIR}/n021003l.pfb
            if [ "$(ls -A ${GSFONTS_DIR})" = ".created-by-flectra-package" ] ; then
                rm -fr ${GSFONTS_DIR}
            fi
    	fi
        ;;

    purge)
        if [ -d "$FLECTRA_LIB_DIR" ]; then
            rm -rf $FLECTRA_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
