#!/bin/sh

set -e

FLECTRA_LIB_DIR=/var/lib/flectra
FLECTRA_USER="flectra"
FLECTRA_GROUP="flectra"

case "${1}" in
    remove)
        deluser --quiet --system $FLECTRA_USER || true
        delgroup --quiet --system --only-if-empty $FLECTRA_GROUP || true
        ;;

    purge)
        if [ -d "$FLECTRA_LIB_DIR" ]; then
            rm -rf $FLECTRA_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
