#!/usr/bin/env python

# Part of code taken from github.com/OCA/maintainer-quality-tools

import os

from coverage.cmdline import main as coverage_main
from coveralls import cli as coveralls_cli
from codecov import main as codecov_main


coverage_main(["report", "--show-missing"])
try:
    coveralls_cli.main(argv=None)
except:
    pass
try:
    codecov_main(argv=None)
except:
    pass
